### ISSUE TITLE
Add note about DuckDB dependency (MacOS)

### ISSUE THREAD

**Issue by darrenwiens** [cholmes/qgis_plugin_gpq_downloader#21]
QGIS version: 3.38.3-Grenoble

I encounter the following error because, afaik, `duckdb` is not distributed within the MacOS Python environment, which is distinct from the system Python environment:

```
Couldn't load plugin 'qgis_plugin_gpq_downloader' 

ModuleNotFoundError: No module named 'duckdb'
```

The following fixes the error for me (installing `duckdb` to the QGIS Python env):

```
/Applications/QGIS.app/Contents/MacOS/bin/python3.9 -m pip install "duckdb==1.1.3"
```

There is another QGIS plugin ([QDuckDB](https://oslandia.gitlab.io/qgis/qduckdb/index.html)) that makes use of duckdb and includes the following note for installation on MacOS: https://oslandia.gitlab.io/qgis/qduckdb/usage/installation.html#macos

As I cannot test the installation on any other OS, I'm hesitant to make the PR to include the note, but I can if that's preferrable.

**Comment by mtravis** [comment]
I was actually using QDuckDB yesterday and I think maybe it ships with DuckDB preinstalled. 

@cholmes you could try packaging DuckDB with the plugin or were you wanting to avoid any dependencies?

Great work in this by the way!

**Comment by cholmes** [comment]
Thanks! Yeah, I think we could add the info directly to the readme. Up until 2 days ago I was using the readme as my issue tracker and then quickly threw it together, so it needs some love. Thanks for catching this and for the first PR! :)
