### ISSUE TITLE
New QGIS Install method

### ISSUE THREAD

**Issue by mtravis** [cholmes/qgis_plugin_gpq_downloader#24]
@cholmes I tried to for and update the wiki but it seems you still can't do that within github. 

I came across a method of installing QGIS on Linux and presumably MAC (not tested) that is super easy and quick. 

In this example I've included duckdb so the plugin will just work when loaded now.  

 ## Pixi

Install [pixi](https://pixi.sh/latest/)

```
pixi init qgis-env
cd qgis-env
pixi add qgis libgdal-arrow-parquet duckdb
pixi shell
```
Then you can run `qgis` from the terminal.

**Comment by cholmes** [comment]
Cool, I added it. Also made you a 'collaborator' so you should be able to edit the wiki now.

**Comment by mtravis** [comment]
Nice one. Thanks for the add too.
