### ISSUE TITLE
Toolbar not appearing in QGIS 3.40

### ISSUE THREAD

**Issue by marklit** [cholmes/qgis_plugin_gpq_downloader#26]
I've got the plugin installed but the 3 buttons aren't appearing in any of the toolbars. Any ideas how I can get them to appear?

<img width="1046" alt="qgis-bin_nAKG8mS7l2" src="https://github.com/user-attachments/assets/f17a26ff-c5df-49bb-892e-4a9c66b39eef">

The data source manager doesn't list anything related to GPQ:

<img width="720" alt="qgis-bin_G54easCJWt" src="https://github.com/user-attachments/assets/f42c1ebe-aee2-4c5f-bb4e-343aa94c5db8">

Nor does the add data sources menu:

<img width="554" alt="qgis-bin_ykAUvHEwP8" src="https://github.com/user-attachments/assets/da603a46-3387-4241-b9e0-a01318c5f219">

**Comment by mtravis** [comment]
@marklit  How have you installed QGIS? You need the libgdal-parqet library too.

**Comment by mtravis** [comment]
I used pixi (inspired by your post a few weeks back)

```
pixi init qgis-env
cd qgis-env
pixi add qgis libgdal-arrow-parquet duckdb
pixi shell
```

Then run `qgis` in that shell.

**Comment by marklit** [comment]
It's the binary for Windows downloaded off of the official QGIS site.  I'm not seeing any complaints about ``libgdal-parquet`` missing. I'm not seeing any errors at all actually. 

I read through the code that adds the menu items in and it looks alright but I'm not versed in writing plugins for QGIS so any less-than-robust UI code wouldn't stand out to me.

**Comment by marklit** [comment]
Found the issue. The first time I installed this, DuckDB wasn't there so QGIS disabled the plugin. I've had to re-enable the plugin and now I can see the toolbar items.

**Comment by cholmes** [comment]
Ah cool. Yeah, seems like #29 may be the best answer.
