### ISSUE TITLE
Install DuckDB before this plugin

### ISSUE THREAD

**Issue by marklit** [cholmes/qgis_plugin_gpq_downloader#27]
It might be worth adding this before the plugin install step so people don't see ugly error messages:

> Before installing this plugin, go to the Plugins Menu -> Python Console. Then type:

``import pip; pip.main(['install', 'duckdb'])``

<img width="528" alt="qgis-bin_80CwezQLE1" src="https://github.com/user-attachments/assets/421118cc-d3e4-4384-a82f-1b43d4c0f5e7">

**Comment by cholmes** [comment]
Ah, cool - that is a nicer way to install it than the instructions I have, will add it soon. Do you know if this works on windows too? I was following qduckdb, and they packaged duckdb for windows, but not for the others.

I'm also curious about just including duckdb directly in the plugin, but don't really understand the tradeoffs and what people normally do with qgis plugins.

**Comment by mtravis** [comment]
@cholmes I would just add DuckDB to the plugin itself. It's not uncommon and solves a lot of headaches with people struggling to install themselves. 

There are ways to build and deploy the plugin and with a pyproject.toml using and include all dependencies there

**Comment by marklit** [comment]
@cholmes yeah, that was on Windows 11.

**Comment by cholmes** [comment]
@marklit - I got errors with this, but it seemed to work:

```
# Use iface to access QGIS API interface or type '?' for more info
# Security warning: typing commands from an untrusted source can harm your computer
import pip; pip.main(['install', 'duckdb'])
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
```

Are those typical? Or just the first time you use it? Want to guide people to be confident that the warnings ok and it worked.

**Comment by marklit** [comment]
QGIS 3.40 ships with Python 3.12.7 and the ``pip.main()`` calls run without issue as far as I can see, albeit with that warning.

I think the way QGIS calls the pip library might be similar to calling the ``virtualenv`` bash script where this sort of warning can come up. If the library believed it was called the same way ``python3 -m venv`` is called that warning wouldn't be seen.

**Comment by mtravis** [comment]
@cholmes I just ran `import pip; pip.main(['install', 'duckdb'])` in my pixi/conda version of QGIS 3.40 it worked fine. 

I had a look into this and think I've got this working now so DuckDB is installed before the plugin initiates. 

Will send a PR over later.

**Comment by cholmes** [comment]
Closing this, #35 and #36 should hopefully do it, we're now just calling this same method in the code.
